# Generated by Django 4.2.13 on 2024-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(upload_to='Bank_App/static')),
                ('password', models.IntegerField()),
                ('confirm_password', models.IntegerField()),
            ],
        ),
    ]
