# Generated by Django 4.2.13 on 2024-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='account_number',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
