# Generated by Django 4.2.13 on 2024-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_App', '0002_signup_model_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
