# Generated by Django 4.2.13 on 2024-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_App', '0003_signup_model_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
