# Generated by Django 4.2.13 on 2024-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_App', '0004_add_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdraw_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
